<?
$aMenuLinks = Array(
    Array(
        "Доставка",
        "/dostavka/",
        Array(),
        Array("DIF_CLASS"=>"delivery"),
        ""
    ),
    Array(
        "Тендеры",
        "/tendery/",
        Array(),
        Array("DIF_CLASS"=>"tenders"),
        ""
    ),
    Array(
        "Новости",
        "/o-kompanii/novosti/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Вакансии",
        "/o-kompanii/vakansii/",
        Array(),
        Array(),
        ""
    )
);
?>