<?
$aMenuLinks = Array(
    Array(
        "Производство",
        "/proizvodstvo/",
        Array(),
        Array("DIF_CLASS"=>"production"),
        ""
    ),
    Array(
        "Лаборатория",
        "/proizvodstvo/laboratoriya/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Сертификаты",
        "/proizvodstvo/sertifikaty/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Дилерам",
        "/proizvodstvo/dileram/",
        Array(),
        Array(),
        ""
    )
);
?>